const PRODUCTS = [
  {
    id: "procedural-dungeon-engine",
    title: "Procedural Dungeon Engine: Roguelike Map Generator",
    subtitle: "Production Python Roguelike generator with 4 generation algorithms, MST pathfinding & 111 unit tests.",
    category: "engine",
    price: 44.99,
    rating: 5.0,
    reviews: 19,
    badges: ["Python 3.10+", "Roguelike Engine", "111 Tests Passing"],
    cover: "assets/covers/dungeonengine.jpg",
    itchUrl: "https://jasonc101.itch.io/procedural-dungeon-engine-roguelike-map-generator",
    gumroadUrl: "https://honeydo5.gumroad.com/",
    description: "Production-grade procedural dungeon generation framework featuring 4 industry-standard algorithms: BSP (Binary Space Partitioning), Cellular Automata, Drunkard's Walk, and Random Walk Caves. Complete with Prim's Algorithm Minimum Spanning Tree corridor connections, A* pathfinding, connectivity validators, seed reproducibility, room decorators, JSON/ASCII/CSV exports, and 111 rigorous automated tests.",
    specs: ["Python 3.10+ Native (Zero External Dependencies)", "Deterministic Seed Reproducibility", "111/111 Pytest Suite Passing", "Royalty-Free Commercial License"]
  },
  {
    id: "so-its-war-then",
    title: "So It's War Then: 4-Faction RTS & Grand Strategy Engine",
    subtitle: "Complete production-grade real-time strategy & empire warfare engine with 4 distinct factions.",
    category: "engine",
    price: 49.99,
    rating: 5.0,
    reviews: 18,
    badges: ["RTS Engine", "4-Faction", "Full Source"],
    cover: "assets/covers/soitswarthen.jpg",
    itchUrl: "https://jasonc101.itch.io/so-its-war-then-4-faction-rts-grand-strategy-engine",
    gumroadUrl: "https://honeydo5.gumroad.com/l/pveflh",
    description: "Battle-tested 4-faction real-time strategy and empire simulation engine. Includes resource economies (Ore, Energy, Biomass), tech trees, formation movement, building construction, and multi-unit AI behavior trees.",
    specs: ["Python / Headless Core", "Deterministic Simulation", "Royalty-Free Commercial License"]
  },
  {
    id: "necros",
    title: "Necros: Godot 4 Dark Fantasy Turn-Based RPG & Combat Framework",
    subtitle: "Turn-based tactical combat framework for Godot 4 with necromancy abilities and grid pathfinding.",
    category: "godot",
    price: 39.99,
    rating: 5.0,
    reviews: 14,
    badges: ["Godot 4", "Dark Fantasy", "Turn-Based RPG"],
    cover: "assets/covers/necros.jpg",
    itchUrl: "https://jasonc101.itch.io/necros-godot-4-dark-fantasy-turn-based-rpg-combat-framework",
    gumroadUrl: "https://honeydo5.gumroad.com/l/dsqeor",
    description: "Complete dark fantasy turn-based RPG architecture for Godot 4. Features a tactical hex/square grid combat arena, soul harvesting mechanics, initiative queues, status effect pipeline, and dark gothic UI.",
    specs: ["Godot 4.2+ Forward+", "GDScript Native", "Commercial License Included"]
  },
  {
    id: "i-got-this",
    title: "I Got This: Godot 4 Open-World 3D Survival & Building Framework",
    subtitle: "67.1 km² deterministic terrain streaming engine, 13-piece modular building system & resource gathering.",
    category: "godot",
    price: 39.99,
    rating: 5.0,
    reviews: 21,
    badges: ["Godot 4", "67km² Terrain", "Base Building"],
    cover: "assets/covers/igotthis.jpg",
    itchUrl: "https://jasonc101.itch.io/i-got-this-godot-4-open-world-3d-survival-building-framework",
    gumroadUrl: "https://honeydo5.gumroad.com/",
    description: "High-performance Godot 4 3D open-world survival game foundation. Features infinite 8192x8192m terrain chunk streaming, full modular building grid with height adjustments and collision validation, dual 1st/3rd person cameras, and JSON persistence.",
    specs: ["Godot 4.5+ Compatible", "Zero External Plugins", "Full Architectural Specs"]
  },
  {
    id: "tactical-grid-combat-engine",
    title: "Tactical Grid Combat Engine: Turn-Based Strategy Framework",
    subtitle: "127 automated unit tests passing in 0.14s. A* pathfinding, line-of-sight & overwatch reaction fire.",
    category: "engine",
    price: 39.99,
    rating: 5.0,
    reviews: 27,
    badges: ["127 Unit Tests", "A* Pathfinding", "Line-of-Sight"],
    cover: "assets/covers/tacticalgrid.jpg",
    itchUrl: "https://jasonc101.itch.io/tactical-grid-combat-engine-turn-based-strategy-framework",
    gumroadUrl: "https://honeydo5.gumroad.com/",
    description: "Production-grade turn-based combat simulation framework (inspired by XCOM and Into the Breach). Features raycasted directional cover calculations, dynamic action point economy, reaction-fire interrupts, and status effects pipeline.",
    specs: ["100% Deterministic", "Headless Simulator", "Royalty-Free Commercial License"]
  },
  {
    id: "mechzilla",
    title: "MechZilla: Tactical Turn-Based Mech Combat & Commander Framework",
    subtitle: "Heavy tactical mech warfare framework for Godot 4 with component damage & heat management.",
    category: "godot",
    price: 39.99,
    rating: 5.0,
    reviews: 16,
    badges: ["Godot 4", "Tactical Mechs", "Turn-Based"],
    cover: "assets/covers/mechzilla.jpg",
    itchUrl: "https://jasonc101.itch.io/mechzilla-tactical-combat-framework",
    gumroadUrl: "https://honeydo5.gumroad.com/l/vcfvti",
    description: "Grid-based mech combat simulator featuring individual limb hitboxes, weapon hardpoints, heat buildup/venting systems, pilot skills, and customizable tactical loadouts in Godot 4.",
    specs: ["Godot 4.2+", "Pure GDScript", "Full Royalty-Free Rights"]
  },
  {
    id: "soldiers-last-stand",
    title: "Soldiers' Last Stand: Modular Squad & Horde Survival Engine",
    subtitle: "Scalable squad combat & swarm AI engine designed for last-stand, horde survival, and tower defense games.",
    category: "engine",
    price: 34.99,
    rating: 5.0,
    reviews: 12,
    badges: ["Squad Combat", "Horde AI", "Wave Spawner"],
    cover: "assets/covers/soldierslaststand.jpg",
    itchUrl: "https://jasonc101.itch.io/soldiers-last-stand-horde-survival-engine",
    gumroadUrl: "https://honeydo5.gumroad.com/l/mefjro",
    description: "High-density enemy flocking and spatial hashing engine capable of managing 1,000+ simultaneous enemies with dynamic target priority, fortification repair, and customizable weapon upgrades.",
    specs: ["Spatial Partitioning", "Optimized CPU Simulation", "Commercial License Included"]
  },
  {
    id: "cyberpunk-warlords",
    title: "Cyberpunk Warlords: Grand Strategy & Auto-Battle RPG Engine",
    subtitle: "22/22 Pytest verified. Fog-of-war overworld, faction diplomacy, town sieges & auto-battle arenas.",
    category: "engine",
    price: 34.99,
    rating: 5.0,
    reviews: 19,
    badges: ["Cyberpunk", "Diplomacy Matrix", "Auto-Battler"],
    cover: "assets/covers/cyberpunkwarlords.jpg",
    itchUrl: "https://jasonc101.itch.io/cyberpunk-warlords-grand-strategy-auto-battle-rpg-engine",
    gumroadUrl: "https://honeydo5.gumroad.com/",
    description: "Complete 2D cyberpunk strategy RPG engine combining overworld fog exploration, bilateral faction diplomacy, territory income and garrison upkeep, moving enemy army AI, automated siege resolution, and deterministic squad auto-battles.",
    specs: ["22 Passing Automated Tests", "Pygame & Headless Ready", "Royalty-Free Source Code"]
  },
  {
    id: "cardsim",
    title: "CardSim: Headless Card Battler & Monte Carlo Balancing Engine",
    subtitle: "Automate card game balance with high-speed headless simulations & win-rate analytics.",
    category: "engine",
    price: 34.99,
    rating: 5.0,
    reviews: 23,
    badges: ["Monte Carlo", "Deckbuilder", "Headless API"],
    cover: "assets/covers/cardsim.jpg",
    itchUrl: "https://jasonc101.itch.io/cardsim-combat-engine",
    gumroadUrl: "https://honeydo5.gumroad.com/l/pvhcq",
    description: "Headless card game engine that runs 100,000 automated card matches in seconds using Monte Carlo trees. Balance mana costs, card draw, damage scaling, and archetype win rates before publishing.",
    specs: ["Lightning Fast Headless", "CSV/JSON Export", "Commercial License Included"]
  },
  {
    id: "hextactics",
    title: "HexTactics: Headless Grid, A* Pathfinding & Combat Engine",
    subtitle: "Mathematical axial hex-grid coordinate engine with line-of-sight algorithms and turn order queues.",
    category: "engine",
    price: 34.99,
    rating: 5.0,
    reviews: 15,
    badges: ["Hex Grid", "A* Pathfinding", "Simulation"],
    cover: "assets/covers/hextactics.jpg",
    itchUrl: "https://jasonc101.itch.io/hextactics-tactical-engine",
    gumroadUrl: "https://honeydo5.gumroad.com/l/eotmup",
    description: "Zero-dependency axial hexagonal grid calculation engine. Features Euclidean and Manhattan distance metrics, Bresenham raycasting line-of-sight, obstacle collision, and initiative queues.",
    specs: ["Zero Dependencies", "Pure Python & TypeScript", "Royalty-Free License"]
  },
  {
    id: "warfront-vault",
    title: "Warfront: 8,000+ Sci-Fi & Alien RTS 2D/3D Isometric Sprite Vault",
    subtitle: "Massive 354 MB asset library containing over 8,000 isometric vehicle, building, and unit sprites.",
    category: "assets",
    price: 29.99,
    rating: 5.0,
    reviews: 31,
    badges: ["8,000+ Sprites", "Sci-Fi RTS", "Isometric Vault"],
    cover: "assets/covers/warfront.jpg",
    itchUrl: "https://jasonc101.itch.io/warfront-8000-sci-fi-alien-rts-2d3d-isometric-sprite-vault",
    gumroadUrl: "https://honeydo5.gumroad.com/l/warfront",
    description: "Over 8,000 transparent PNG isometric assets organized across 8 directional angles for sci-fi tanks, walkers, aircraft, alien bio-constructs, command centers, turrets, and resource extractors.",
    specs: ["354 MB Compressed Vault", "Transparent PNGs", "Unlimited Commercial Projects"]
  },
  {
    id: "relics-of-the-abyss",
    title: "Relics of the Abyss: 650+ Dark Fantasy RPG Assets & Textures Vault",
    subtitle: "588 MB museum-grade collection: ancient relics, occult runes, undead monsters & seamless surfaces.",
    category: "assets",
    price: 24.99,
    rating: 5.0,
    reviews: 29,
    badges: ["650+ Assets", "Dark Fantasy", "4K Textures"],
    cover: "assets/covers/relicsabyss.jpg",
    itchUrl: "https://jasonc101.itch.io/relics-of-the-abyss-650-dark-fantasy-rpg-assets-textures-vault",
    gumroadUrl: "https://honeydo5.gumroad.com/",
    description: "Expansive 658-asset dark fantasy vault featuring occult runes, abyssal weapons, cursed amulets, undead colossi portraits, and high-res gothic cobblestone, dark oak, and weathered stone textures.",
    specs: ["588 MB Lossless Pack", "Ready for Godot/Unity/Unreal", "Royalty-Free License"]
  },
  {
    id: "wildlands-protocol",
    title: "Wildlands Protocol: Godot 4 3D Mech Locomotion & Urban Sandbox Kit",
    subtitle: "3D battle mech action starter kit for Godot 4: 6-DOF locomotion, boost thrusters & procedural cities.",
    category: "godot",
    price: 24.99,
    rating: 5.0,
    reviews: 11,
    badges: ["Godot 4", "3D Mech Kit", "Procedural City"],
    cover: "assets/covers/wildlands.jpg",
    itchUrl: "https://jasonc101.itch.io/wildlands-protocol-godot-4-3d-mech-locomotion-urban-sandbox-kit",
    gumroadUrl: "https://honeydo5.gumroad.com/",
    description: "Out-of-the-box 3D mech action starter kit. Features responsive mech movement, jump jet thrusters, spring-arm third-person camera, forward+ rendering materials, and procedural city street generator.",
    specs: ["Godot 4.2+ Forward+", "GDScript Native", "Full Commercial Rights"]
  },
  {
    id: "voidrogue",
    title: "VoidRogue: Production TypeScript Roguelike Deckbuilder Engine",
    subtitle: "Modular turn-based card combat architecture with relics, deck synergies, and procedural map generation.",
    category: "engine",
    price: 24.99,
    rating: 5.0,
    reviews: 17,
    badges: ["TypeScript", "Roguelike", "Deckbuilder"],
    cover: "assets/covers/voidrogue.jpg",
    itchUrl: "https://jasonc101.itch.io/voidrogue-production-typescript-roguelike-deckbuilder-engine",
    gumroadUrl: "https://honeydo5.gumroad.com/l/pvlfg",
    description: "Production-ready TypeScript architecture for card battlers (inspired by Slay the Spire). Features node-based dungeon progression, relic triggers, status effects, and reactive combat event loop.",
    specs: ["Clean TypeScript Core", "Web / Electron / Node Ready", "Royalty-Free License"]
  },
  {
    id: "necrobestiary",
    title: "NecroBestiary: Dark Fantasy Undead & Bosses 2D Sprite Pack",
    subtitle: "Handcrafted 2D sprite pack featuring skeletons, wraiths, liches, bone dragons, and abyssal horrors.",
    category: "assets",
    price: 19.99,
    rating: 5.0,
    reviews: 20,
    badges: ["Undead Bosses", "2D Sprites", "Dark Fantasy"],
    cover: "assets/covers/necrobestiary.jpg",
    itchUrl: "https://jasonc101.itch.io/necrobestiary-dark-fantasy-undead-bosses-2d-sprite-pack",
    gumroadUrl: "https://honeydo5.gumroad.com/l/qgoxea",
    description: "60+ high-resolution transparent PNG monster sprites with multi-layered weapon accessories and spectral visual effects tailored for dark fantasy RPGs and dungeon crawlers.",
    specs: ["High-Res Transparent PNG", "Individual & Atlas Sheets", "Royalty-Free License"]
  },
  {
    id: "mechdominion",
    title: "MechDominion: Cybernetic Titans & Mecha Bosses 2D Sprite Pack",
    subtitle: "Futuristic mechs, walking war machines, automated drones, and cybernetic siege boss sprites.",
    category: "assets",
    price: 19.99,
    rating: 5.0,
    reviews: 14,
    badges: ["Mecha Titans", "Cybernetic Bosses", "Transparent PNG"],
    cover: "assets/covers/mechdominion.jpg",
    itchUrl: "https://jasonc101.itch.io/mechdominion-titans-bosses-sprite-pack",
    gumroadUrl: "https://honeydo5.gumroad.com/l/dqdhpi",
    description: "Precision-designed mecha titan sprites with separate weapons, missile racks, laser cannons, and tread modules ready to animate and assemble in any 2D game engine.",
    specs: ["Layered Modular Parts", "Clean Vector & PNG", "Full Commercial License"]
  },
  {
    id: "slay-the-void",
    title: "Slay The Void: Cosmic Sci-Fi & Dark RPG Card Art Pack",
    subtitle: "Over 200 illustrated cosmic horror and cybernetic sci-fi card illustrations for deckbuilder games.",
    category: "assets",
    price: 19.99,
    rating: 5.0,
    reviews: 22,
    badges: ["Cosmic Horror", "Sci-Fi Cards", "High-Res Art"],
    cover: "assets/covers/slaythevoid.jpg",
    itchUrl: "https://jasonc101.itch.io/slay-the-void-cosmic-sci-fi-dark-rpg-card-art-pack",
    gumroadUrl: "https://honeydo5.gumroad.com/l/pvlfg",
    description: "200+ unique card art illustrations in standard trading card ratios (750x1050 and 1500x2100). Divided into Attack, Defense, Skill, Relic, and Eldritch Curse categories.",
    specs: ["Standard Card Aspect Ratio", "High DPI Print Ready", "Commercial License Included"]
  },
  {
    id: "grimrealm",
    title: "GrimRealm: RPG Terrains & Environment Textures (79 Pack)",
    subtitle: "79 seamless 2K and 4K tiling dark fantasy landscape and architectural surface textures.",
    category: "assets",
    price: 14.99,
    rating: 5.0,
    reviews: 19,
    badges: ["79 Textures", "Seamless Tiling", "Dark Gothic"],
    cover: "assets/covers/grimrealm.jpg",
    itchUrl: "https://jasonc101.itch.io/grimrealm-rpg-terrains-environment-textures-79-pack",
    gumroadUrl: "https://honeydo5.gumroad.com/l/szhlm",
    description: "79 seamless tiling surface textures including ancient stone masonry, muddy battlefields, crypt floors, mossy tomb walls, and corrupted earth with PBR-ready details.",
    specs: ["2048x2048 & 4096x4096", "Seamlessly Tiling", "Commercial License Included"]
  },
  {
    id: "we-got-this",
    title: "WE GOT THIS!: Narrative Fallout Shelter Survival Game",
    subtitle: "Standalone commercial game build. 28-day narrative arc, 4 acts, 6 endings, and 18 achievements.",
    category: "game",
    price: 14.99,
    rating: 5.0,
    reviews: 35,
    badges: ["Full Game", "Windows Standalone", "6 Endings"],
    cover: "assets/covers/wegotthis.jpg",
    itchUrl: "https://jasonc101.itch.io/we-got-this-narrative-fallout-shelter-survival-game",
    gumroadUrl: "https://honeydo5.gumroad.com/",
    description: "Complete playable narrative survival-management game. Lead two families through the final weeks of a failing fallout shelter beneath the ruined city of Bellwether. 28 in-game days, tactile expedition planning board, 18 achievements, full accessibility options, and controller support.",
    specs: ["Standalone Windows Executable", "Native 1080p / 4K Scaling", "Complete Story Experience"]
  },
  {
    id: "glyphcore-icons",
    title: "GlyphCore Icons Pro: 200+ Clean Modern Vector UI Icons",
    subtitle: "200+ precision-crafted SVG vector icons tailored for game menus, HUDs, action bars & apps.",
    category: "assets",
    price: 14.99,
    rating: 5.0,
    reviews: 26,
    badges: ["200+ Icons", "Scalable SVG", "Game UI & HUD"],
    cover: "assets/covers/glyphcore.jpg",
    itchUrl: "https://jasonc101.itch.io/glyphcore-icons-pro-200-clean-modern-vector-ui-icons",
    gumroadUrl: "https://honeydo5.gumroad.com/",
    description: "Handcrafted, precision-engineered vector icon collection organized across Navigation, Combat/Stats, Controls, Inventory, Media, and System categories. Standard 24x24 and 32x32 bounding boxes for crisp rendering at any DPI.",
    specs: ["Clean Semantic SVG", "React/Vue/Godot/Unity Ready", "Royalty-Free License"]
  },
  {
    id: "humans-endless-warmonger",
    title: "Humans: The Endless Warmonger by Jason Coleman",
    subtitle: "Complete military philosophy manuscript (.docx & .md), worldbuilding bible & KDP launch kit.",
    category: "book",
    price: 9.99,
    rating: 5.0,
    reviews: 42,
    badges: ["Full Manuscript", "Lore Bible", "Military History"],
    cover: "assets/covers/humansendless.jpg",
    itchUrl: "https://jasonc101.itch.io/humans-the-endless-warmonger-by-jason-coleman",
    gumroadUrl: "https://honeydo5.gumroad.com/",
    description: "An unsparing forensic autopsy of humanity's 5,000-year ledger of warfare by author Jason Coleman. Examines the biological operating system of conflict and introduces the five technological pillars of post-human peace.",
    specs: ["Complete DOCX & Markdown", "Story Bible & Timeline", "Full Commercial Launch Kit"]
  }
];
